### ISSUE TITLE
what‘s the special function of mhdf5.lua

### ISSUE THREAD

**Issue by lupantech** [jnhwkim/MulLowBiVQA#10]
@jnhwkim  Hi, I am new to Lua. I find that you define mhdf5.lua to read the image feature. I am a little confused about the function of mhdf5.lua: why not get the image feature directly by using : `h5_file:read()`?

**Comment by jnhwkim** [comment]
@lupantech you can do that. that script is just caching image features to cpu memory. it speeds up little bit.
