### ISSUE TITLE
Skip thoughts question embeddings

### ISSUE THREAD

**Issue by idansc** [jnhwkim/MulLowBiVQA#7]
Hi, can you please give more information about the pretrained corpus that you used. The DPP paper only mentions Huge corpus, but he is not specific. 
Moreover, do you have results without the pre-trained model so we can have comparable score? 

Thanks in advance

**Comment by jnhwkim** [comment]
@idansc I think you're talking about the use of pretrained Skip-thought vectors model as a question encoder. In that case, the corpus is `BookCorpus` dataset (Zhu et al., 2015). The one of notable discovery in DPPnet by Noh et al. (2015) is the use of Skip-thought vectors model as a question encoder, however, I've heard that, for some architecture or task, it doesn't much helpful for performance (via personal communications, no reference for this, yet.). For MLB, we don't have comparable score but our previous work [MRN](https://papers.nips.cc/paper/6446-multimodal-residual-learning-for-visual-qa) (Kim et al., 2016b), which has a similar structure but without attention mechanism did the comparison in Supplemental. That gives around 0.40% improvement.
