### ISSUE TITLE
Generating gru.t7

### ISSUE THREAD

**Issue by ahmedmagdiosman** [jnhwkim/MulLowBiVQA#9]
Hello,

I can't figure out how to generate the `gru.t7` torch file.
`003_skipthoughts_porting` generates `vqa_uni_gru_word2vec.t7`
However this seems to be only a torch tensor without the `rnn`'s GRU object.

Can you please let me know how you generate the gru.t7 file?
I am generating skipthoughts for trainval.

My steps:
1. Downloaded skipt thought tables
2. Run make_lookuptable.lua to generate `vocab_2k.txt`
3. Copy `vocab_2k.txt` to  `skipthoughts_porting/`
4. Edit `002_writevocab_table_vqa.py` line 57 to use `vocab_2k.txt`
5. Run `002_writevocab_table_vqa.py` 
6. Run `th 004_save_params_in_torch_file_vqa.lua`
7. Rerun make `lookuptable.lua `to generate lookup_2k.t7
8. Copy and rename `vqa_uni_gru_word2vec.t7` to `gru.t7`
9. move `lookup_2k.t7` and  `gru.t7` to skipthoughts_model
10. `th train.lua`

Thanks in advance! :)

**Comment by jnhwkim** [comment]
@ahmedmagdiosman a quick answer is to copy those parameters to GRU. You can access six tensors as follows:
```
model = nn.GRU(inputSize, outputSize)
w,dw = a.recurrentModule:parameters()
```
`w` is a table of parameter tensors:
```
w[1] : DoubleTensor - size: [outputSizex2]x[inputSize]
w[2] : DoubleTensor - size: [outputSizex2] 
w[3] : DoubleTensor - size: [outputSizex2]x[outputSize]
w[4] : DoubleTensor - size: [outputSizex]x[inputSize]
w[5] : DoubleTensor - size: [outputSize]
w[6] : DoubleTensor - size: [outputSize]x[outputSize]
```
Every tensor has a different shape, so, you can check the correctness by that.
```
w[i]:copy(new_param_tensor[i])
```
may work.

**Comment by ahmedmagdiosman** [comment]
@jnhwkim  Thanks for your input, but I seem to be still stuck.

When I load the parameters from `uni_gru_params.t7` , they don't seem to match with a GRU of input  size 620 and output size of 2400.

Here's what I have done:

` p = torch.load('uni_gru_params.t7' )`
` m = torch.load('vqa_uni_gru_word2vec.t7' )`

`model = nn.GRU(620, 2400)`
 `w,dw = model.recurrentModule:parameters()`

`th> w`
`  1 : DoubleTensor - size: 4800x620`
`  2 : DoubleTensor - size: 4800`
`  3 : DoubleTensor - size: 4800x2400`
`  4 : DoubleTensor - size: 2400x620`
`  5 : DoubleTensor - size: 2400`
`  6 : DoubleTensor - size: 2400x2400`


`th> p`
`  Ux : FloatTensor - size: 2400x2400`
`  W : FloatTensor - size: 620x4800`
`  Wx : FloatTensor - size: 620x2400`
`  b : FloatTensor - size: 4800`
`  bx : FloatTensor - size: 2400`
`  U : FloatTensor - size: 2400x4800`

`th> m:size(1)`
`  12827`
`th> m:size(2)`
`  620`

Do you have an idea what am I doing wrong?

**Comment by jnhwkim** [comment]
For example,
```
w[1]:copy(p['W']:t())
w[2]:copy(p['b'])
w[3]:copy(p['U']:t())
...
```
For `m`, see [this](https://github.com/jnhwkim/MulLowBiVQA/blob/master/make_lookuptable.lua#L50):
```
require 'rnn'
tmp=torch.load('../DPPnet/003_skipthoughts_porting/data/skipthoughts_params/vqa_uni_gru_word2vec.t7')
lookup = nn.LookupTableMaskZero(vocab_size,620)
assert(lookup.weight:size(1) == vocab_size+1)
assert(lookup.weight:size(2) == 620)
assert(tmp:size(2) == 620)
-- weight[1] is zero, tmp's last row is for <eos>.
lookup.weight[1]:zero()
lookup.weight:narrow(1,2,vocab_size):copy(tmp:narrow(1,1,vocab_size));
torch.save('lookup_2k.t7', lookup)
```

**Comment by ahmedmagdiosman** [comment]
Thanks a lot it worked!
